[Distribution]
Distribution=centos
Release=10

[Output]
OutputDirectory=mkosi.output
Format=none

[Build]
ToolsTree=default
ToolsTreeRelease=10
ToolsTreeRepositories=epel
ToolsTreeDistribution=centos
ToolsTreePackages=systemd-repart,distribution-gpg-keys
ToolsTreeSandboxTrees=
CacheDirectory=mkosi.cache
Incremental=yes
